stages:
  visualize_data:
    cmd: python src/data_visualization.py
    deps:
      - data/raw/bank-additional-full.csv
      - src/data_visualization.py
  test_data_quality:
    cmd: pytest test/test_data_quality.py
    deps:
      - test/test_data_quality.py
      - data/raw/bank-additional-full.csv
  test_data_gx:
    cmd: pytest test/test_data_gx.py
    deps:
      - test/test_data_gx.py
      - data/raw/bank-additional-full.csv