stages:
  visualize_data:
    cmd: python src/data_visualization.py
    deps:
      - data/raw/bank-additional-full.csv
      - src/data_visualization.py
  test_data_quality:
    cmd: pytest test/test_data_quality.py
    deps:
      - test/test_data_quality.py
      - data/raw/bank-additional-full.csv
  test_data_gx:
    cmd: pytest test/test_data_gx.py
    deps:
      - test/test_data_gx.py
      - data/raw/bank-additional-full.csv
  preprocess_data:
    cmd: python src/data_preparation.py
    deps:
      - src/data_preparation.py
      - data/raw/bank-additional-full.csv
  train_model:
    cmd: python src/train_model.py
    deps:
      - src/train_model.py
      - data/processed/bank-processed.csv
  train_test:
    cmd: pytest test/test_training.py
    deps:
      - test/test_training.py
      - data/processed/bank-processed.csv